name: eduwlc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
  - assets/



